package com.sampleAuth.mybatis.bean;

import java.io.Serializable;

public class Auth implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auth.id
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auth.phone
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auth.security_code
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	private String securityCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auth.expires_at
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	private Long expiresAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auth.status
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	private Byte status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auth.created
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	private Long created;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auth.updated
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	private Long updated;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table auth
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auth.id
	 * @return  the value of auth.id
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auth.id
	 * @param id  the value for auth.id
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auth.phone
	 * @return  the value of auth.phone
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auth.phone
	 * @param phone  the value for auth.phone
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auth.security_code
	 * @return  the value of auth.security_code
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	public String getSecurityCode() {
		return securityCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auth.security_code
	 * @param securityCode  the value for auth.security_code
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	public void setSecurityCode(String securityCode) {
		this.securityCode = securityCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auth.expires_at
	 * @return  the value of auth.expires_at
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	public Long getExpiresAt() {
		return expiresAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auth.expires_at
	 * @param expiresAt  the value for auth.expires_at
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	public void setExpiresAt(Long expiresAt) {
		this.expiresAt = expiresAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auth.status
	 * @return  the value of auth.status
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auth.status
	 * @param status  the value for auth.status
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auth.created
	 * @return  the value of auth.created
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	public Long getCreated() {
		return created;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auth.created
	 * @param created  the value for auth.created
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	public void setCreated(Long created) {
		this.created = created;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auth.updated
	 * @return  the value of auth.updated
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	public Long getUpdated() {
		return updated;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auth.updated
	 * @param updated  the value for auth.updated
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	public void setUpdated(Long updated) {
		this.updated = updated;
	}
}