package com.sampleAuth.mybatis.bean;

import java.io.Serializable;

public class Session implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column session.id
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column session.user_id
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column session.token
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	private String token;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column session.phone
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column session.expires_at
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	private Long expiresAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column session.created
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	private Long created;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column session.updated
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	private Long updated;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table session
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column session.id
	 * @return  the value of session.id
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column session.id
	 * @param id  the value for session.id
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column session.user_id
	 * @return  the value of session.user_id
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column session.user_id
	 * @param userId  the value for session.user_id
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column session.token
	 * @return  the value of session.token
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	public String getToken() {
		return token;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column session.token
	 * @param token  the value for session.token
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	public void setToken(String token) {
		this.token = token;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column session.phone
	 * @return  the value of session.phone
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column session.phone
	 * @param phone  the value for session.phone
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column session.expires_at
	 * @return  the value of session.expires_at
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	public Long getExpiresAt() {
		return expiresAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column session.expires_at
	 * @param expiresAt  the value for session.expires_at
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	public void setExpiresAt(Long expiresAt) {
		this.expiresAt = expiresAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column session.created
	 * @return  the value of session.created
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	public Long getCreated() {
		return created;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column session.created
	 * @param created  the value for session.created
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	public void setCreated(Long created) {
		this.created = created;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column session.updated
	 * @return  the value of session.updated
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	public Long getUpdated() {
		return updated;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column session.updated
	 * @param updated  the value for session.updated
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	public void setUpdated(Long updated) {
		this.updated = updated;
	}
}