package com.sampleAuth.mybatis.mappers;

import com.sampleAuth.mybatis.bean.Auth;
import com.sampleAuth.mybatis.bean.AuthExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AuthMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auth
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	int countByExample(AuthExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auth
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	int deleteByExample(AuthExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auth
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auth
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	int insert(Auth record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auth
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	int insertSelective(Auth record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auth
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	List<Auth> selectByExample(AuthExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auth
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	Auth selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auth
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	int updateByExampleSelective(@Param("record") Auth record, @Param("example") AuthExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auth
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	int updateByExample(@Param("record") Auth record, @Param("example") AuthExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auth
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	int updateByPrimaryKeySelective(Auth record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auth
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	int updateByPrimaryKey(Auth record);
}