package com.sampleAuth.mybatis.mappers;

import com.sampleAuth.mybatis.bean.Session;
import com.sampleAuth.mybatis.bean.SessionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SessionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table session
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	int countByExample(SessionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table session
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	int deleteByExample(SessionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table session
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table session
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	int insert(Session record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table session
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	int insertSelective(Session record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table session
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	List<Session> selectByExample(SessionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table session
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	Session selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table session
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	int updateByExampleSelective(@Param("record") Session record, @Param("example") SessionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table session
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	int updateByExample(@Param("record") Session record, @Param("example") SessionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table session
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	int updateByPrimaryKeySelective(Session record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table session
	 * @mbggenerated  Tue Mar 22 14:33:36 IST 2016
	 */
	int updateByPrimaryKey(Session record);
}